### ISSUE TITLE
p4 programming / naming convention proposal

### ISSUE THREAD

**Issue by frederic-loui** [rare-freertr/RARE-bmv2#1]
Hi, during our work we will write P4 program and make the code as much as modular and reusable. After having studied several source codes please find several suggestions:
* have the source code in a `p4src` folder
* have an `include` directory in `p4src` in order to make the program modular
* have in `include`, a file called `ethertype.p4` in which all ethertype are listed
    * [Source: IEEE 802 numbers](https://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers.xhtml)
* have in `include`, a file called `ip-ptotocol.p4` in which all ip protocol are listed
    * [Source: Protocol Numbers](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml)
* prefix `parser` block with `prs_`
* prefix `control` block with `ctl_`
* prefix `table` block with `tbl_`
* prefix `action` block with `act_`
The idea behind this naming convention is to make the code readable from a beginner perspective.   

This thread is just to initiate the discussion. All the proposed items above can be changed overtime.

**Comment by jordiortizumu** [comment]
in ip-protocol.p4 and ethertype.p4 should be only the used ones, I guess... If not it may make sense having them in an include outside the use case.

**Comment by frederic-loui** [comment]
Yes ! you 100% right Jordi. The idea in this repository, is to have these files as reference. Just include them for the LAB, test, etc. In real production we can stick with only the used ones. (i.e a subset of these files) If you look at `switch.p4`, there are similar files that list exhaustively these `ETHERTYPE` and `PROTOCOL_NUMBER`. Anyway, I put an example on how to use these files in the first Lab. (`0001-unoptimized-ipv4-forwarding`)

**Comment by mc36** [comment]
sorry? :)
