### ISSUE TITLE
FreeRTR control plane and P4 switch dataplane interface implementation

### ISSUE THREAD

**Issue by frederic-loui** [rare-freertr/RARE-bmv2#20]
As per week #33 VC, we need to have a general concensus and understanding on how to implement the communication between the control plane(FreeRTR) and the data plane(P4 switch).

The current implementation works, and is great so that all team members can start focusing on implementing unit labs that will compose future NREN use case. But even if it is a good pedagogic exercise the target objective is to implement on bmv2/simple_switch_grpc, a interface similar to the one we would implement on bf_switchd. (BAREFOOT TOFINO switch) 

It is unclear to me if:

1- We have a direct switch connection + GRPC interface
2- We have a GRPC connection and aside P4 communication, the control plane discussion takes place pver this GRPC link.

I'm then seeking the opinion and reaction from the team participant related to that topic.
The idea is to track and target the final implementation toward simple_switch_grpc and bf_swictchd.

**Comment by mc36** [comment]
it get implemented afteralll....
