### ISSUE TITLE
Spurious errors from ethtool when starting freertr

### ISSUE THREAD

**Issue by alexandergall** [rare-freertr/RARE-bmv2#5]
Runnin `make` in `00-unit-labs/0000-topology` executes some `ethtool` tweaks for the `veth` interfaces. Some of them fail, e.g.
```
--- DECLARING FREERTR INTERFACE RAWINT (FORWARDING PLANE) ---
Actual changes:
tx-checksumming: off
        tx-checksum-ip-generic: off
tcp-segmentation-offload: off
        tx-tcp-segmentation: off [requested on]
        tx-tcp-ecn-segmentation: off [requested on]
        tx-tcp6-segmentation: off [requested on]
udp-fragmentation-offload: off [requested on]
Actual changes:
scatter-gather: off
        tx-scatter-gather: off
        tx-scatter-gather-fraglist: off
generic-segmentation-offload: off [requested on]
Cannot change large-receive-offload
Cannot change ntuple-filters
Cannot change receive-hashing
Cannot get EEE settings: Operation not supported
```
I'm not sure whether that's because those options simply not exist on these interfaces or something is wrong. If it's normal behaviour, we should remove those settings to avoid the error messages.

**Comment by frederic-loui** [comment]
Yes, these are "normal" errors observed from `ethtool`. These are usually the basic commands sequence recommended to apply in order to fix tcp offload issue on linux. And this depend on the default network configuration on the kernel.

**Comment by mc36** [comment]
sorry?sorry?sorry?sorry?sorry?sorry?sorry?sorry?sorry?sorry?sorry?sorry?sorry?sorry? :))))
